version: "3.8"

services:
  mongodb:
    profiles: ["local-dev", "container-dev"]
    image: mongo:5.0.4
    restart: always
    container_name: MongoDB
    build:
      dockerfile: /docker/Mongo
      context: .
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
  rabbitmq:
    profiles: ["local-dev", "container-dev"]
    image: rabbitmq:3.8.25-alpine
    restart: always
    container_name: RabbitMQ
    ports:
      - ${RABBITMQ_PORT}:5672
  nestjs:
    profiles: ["container-dev"]
    image: node:lts-alpine3.14
    restart: always
    container_name: Nest.JS
    ports:
      - ${NESTJS_PORT}:3000
    build:
      dockerfile: /docker/Nest
      context: .
    volumes:
      - .:/app
      - node_modules:/app/src/node_modules
    depends_on:
      - mongodb
      - rabbimq

volumes:
  node_modules: {}
