version: "3.8"

services:
  mongodb:
    image: mongo:5.0.4
    restart: always
    container_name: MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
  rabbitmq:
    image: rabbitmq:3.8.25-alpine
    restart: always
    container_name: RabbitMQ
    ports:
      - ${RABBITMQ_PORT}:5672
