version: "3.8"

services:
  nestjs_dev:
    profiles: ["dev-container", "all"]
    image: myt/back-end:dev
    container_name: Nest.JS-Dev
    ports:
      - ${NESTJS_PORT}:3000
    build:
      dockerfile: ./docker/Nest_Dev_Dockerfile
      context: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./dist:/app/dist
    depends_on:
      - mongodb_dev
      - rabbitmq_dev
    environment:
      - NESTJS_PORT=3000
      - MONGO_ENDPOINT=mongodb
      - MONGO_PORT=27017
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INIT_DB=${MONGO_INIT_DB}
      - RABBITMQ_ENDPOINT=rabbitmq
      - RABBITMQ_PORT=5672
      - AUTOMATE_ENDPOINT=rust
      - AUTOMATE_PORT=3030
      - GATEWAY_ENDPOINT=tsed
      - GATEWAY_PORT=8080
    networks:
      default:
        aliases:
          - nestjs
          - nestjs_dev
  nestjs_prod:
    profiles: ["all", "prod"]
    image: myt/back-end:prod
    container_name: Nest.JS-Prod
    ports:
      - ${NESTJS_PORT}:3000
    build:
      dockerfile: ./docker/Nest_Prod_Dockerfile
      context: .
    depends_on:
      - mongodb_dev
      - mongodb_prod
      - rabbitmq_dev
      - rabbitmq_prod
    environment:
      - NESTJS_PORT=3000
      - MONGO_ENDPOINT=mongodb
      - MONGO_PORT=27017
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INIT_DB=${MONGO_INIT_DB}
      - RABBITMQ_ENDPOINT=rabbitmq
      - RABBITMQ_PORT=5672
      - AUTOMATE_ENDPOINT=rust
      - AUTOMATE_PORT=3030
      - GATEWAY_ENDPOINT=tsed
      - GATEWAY_PORT=8080
    networks:
      default:
        aliases:
          - nestjs
          - nestjs_prod
  
  rabbitmq_dev:
    profiles: ["dev-local", "dev-container", "all"]
    image: rabbitmq:3.9.10-management-alpine
    container_name: RabbitMQ-Dev
    ports:
      - ${RABBITMQ_EXTERNAL_PORT}:5672
      - ${RABBITMQ_EXTERNAL_MANAGEMENT_PORT}:15672
    networks:
      default:
        aliases:
          - rabbitmq
          - rabbitmq_dev
  rabbitmq_prod:
    profiles: ["prod", "all"]
    image: rabbitmq:3.9.10-alpine
    container_name: RabbitMQ-Prod
    networks:
      default:
        aliases:
          - rabbitmq
          - rabbitmq_prod
  
  mongodb_dev:
    profiles: ["dev-local", "dev-container", "all"]
    image: myt/back-end-db:1.0
    container_name: MongoDB-Dev
    build:
      dockerfile: ./docker/Mongo_Dockerfile
      context: .
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INIT_DB: ${MONGO_INIT_DB}
    ports:
      - ${MONGO_EXTERNAL_PORT}:27017
    networks:
      default:
        aliases:
          - mongodb_dev
          - mongodb
  mongodb_prod:
    profiles: ["prod", "all"]
    image: mongo:5.0.4
    container_name: MongoDB-Prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INIT_DB: ${MONGO_INIT_DB}
    networks:
      default:
        aliases:
          - mongodb_prod
          - mongodb

networks:
  default:
    name: myt
