version: "3.8"

services:
  nestjs_dev:
    profiles: ["dev-container", "all"]
    image: myt/back-end:dev
    container_name: Nest.JS-Dev
    ports:
      - ${NESTJS_EXPOSE_PORT}:${NESTJS_PORT}
    build:
      dockerfile: ./docker/Nest_Dev_Dockerfile
      context: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./dist:/app/dist
    depends_on:
      - mongodb_dev
      - rabbitmq_dev
    environment:
      - NESTJS_PORT=${NESTJS_PORT}
      - MONGO_ENDPOINT=${DOCKER_MONGO_ENDPOINT}
      - MONGO_PORT=${DOCKER_MONGO_PORT}
      - MONGO_USERNAME=${DOCKER_MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${DOCKER_MONGO_ROOT_PASSWORD}
      - MONGO_DB=${DOCKER_MONGO_INIT_DB}
      - MONGO_OPTIONS=${DOCKER_MONGO_OPTIONS}
      - RABBITMQ_ENDPOINT=${DOCKER_RABBITMQ_ENDPOINT}
      - RABBITMQ_PORT=${DOCKER_RABBITMQ_PORT}
      - AUTOMATE_ENDPOINT=${DOCKER_AUTOMATE_ENDPOINT}
      - AUTOMATE_PORT=${DOCKER_AUTOMATE_PORT}
      - GATEWAY_ENDPOINT=${DOCKER_GATEWAY_ENDPOINT}
      - GATEWAY_PORT=${DOCKER_GATEWAY_PORT}
    networks:
      default:
        aliases:
          - nestjs
          - nestjs_dev
  nestjs_prod:
    profiles: ["all", "prod"]
    image: moveyourtable.azurecr.io/back-end
    container_name: Nest.JS-Prod
    ports:
      - ${NESTJS_EXPOSE_PORT}:${NESTJS_PORT}
    build:
      dockerfile: ./docker/Nest_Prod_Dockerfile
      context: .
    depends_on:
      - mongodb_dev
      - mongodb_prod
      - rabbitmq_dev
      - rabbitmq_prod
    environment:
      - NESTJS_PORT=${NESTJS_PORT}
      - MONGO_ENDPOINT=${DOCKER_MONGO_ENDPOINT}
      - MONGO_PORT=${DOCKER_MONGO_PORT}
      - MONGO_USERNAME=${DOCKER_MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${DOCKER_MONGO_ROOT_PASSWORD}
      - MONGO_DB=${DOCKER_MONGO_INIT_DB}
      - MONGO_OPTIONS=${DOCKER_MONGO_OPTIONS}
      - RABBITMQ_ENDPOINT=${DOCKER_RABBITMQ_ENDPOINT}
      - RABBITMQ_PORT=${DOCKER_RABBITMQ_PORT}
      - AUTOMATE_ENDPOINT=${DOCKER_AUTOMATE_ENDPOINT}
      - AUTOMATE_PORT=${DOCKER_AUTOMATE_PORT}
      - GATEWAY_ENDPOINT=${DOCKER_GATEWAY_ENDPOINT}
      - GATEWAY_PORT=${DOCKER_GATEWAY_PORT}
    networks:
      default:
        aliases:
          - nestjs
          - nestjs_prod
  
  rabbitmq_dev:
    profiles: ["dev-local", "dev-container", "all"]
    image: rabbitmq:3.9.10-management-alpine
    container_name: RabbitMQ-Dev
    ports:
      - ${DOCKER_RABBITMQ_EXTERNAL_PORT}:5672
      - ${DOCKER_RABBITMQ_EXTERNAL_MANAGEMENT_PORT}:15672
    networks:
      default:
        aliases:
          - rabbitmq
          - rabbitmq_dev
  rabbitmq_prod:
    profiles: ["prod", "all"]
    image: rabbitmq:3.9.10-alpine
    container_name: RabbitMQ-Prod
    networks:
      default:
        aliases:
          - rabbitmq
          - rabbitmq_prod
  
  mongodb_dev:
    profiles: ["dev-local", "dev-container", "all"]
    image: myt/back-end-db:1.0
    container_name: MongoDB-Dev
    build:
      dockerfile: ./docker/Mongo_Dockerfile
      context: .
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_ROOT_PASSWORD}
      MONGO_INIT_DB: ${DOCKER_MONGO_INIT_DB}
    ports:
      - ${DOCKER_MONGO_EXTERNAL_PORT}:27017
    networks:
      default:
        aliases:
          - mongodb_dev
          - mongodb
  mongodb_prod:
    profiles: ["prod", "all"]
    image: mongo:5.0.4
    container_name: MongoDB-Prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_ROOT_PASSWORD}
      MONGO_INIT_DB: ${DOCKER_MONGO_INIT_DB}
    networks:
      default:
        aliases:
          - mongodb_prod
          - mongodb

networks:
  default:
    name: myt
